{% set version = "0.4" %}

package:
  name: scikit-sparse
  version: {{ version }}

source:
  fn: scikit-sparse-{{ version }}.tar.gz
  url: https://github.com/scikit-sparse/scikit-sparse/archive/v{{ version }}.tar.gz
  sha256: 50aa2b9a18a386f77569ad30f48b74221e1f6c878fbd41d6644a1a63ce5859eb

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - python
    - numpy x.x
    - suitesparse
    - cython
    - setuptools
  run:
    - python
    - numpy x.x
    - scipy
    - suitesparse

test:
  requires:
    - nose
    - setuptools
  imports:
    - sksparse
    - sksparse.cholmod
  commands:
    - OPENBLAS_NUM_THREADS=1 nosetests -sv sksparse

about:
  home: https://github.com/scikit-sparse/scikit-sparse
  license: BSD 2-clause
  summary: A companion to the scipy.sparse library for sparse matrix manipulation in Python.

extra:
    recipe-maintainers:
      - grlee77
      - patricksnape
      - jor-
