travis:
  secure:
    BINSTAR_TOKEN: R/rMNG+N+pWYRHE7szERL39tfSKMbiiW8V8KUYZSJGb6oRzwQnMnXot7HmY2Sb5TYQ39D3IYrfvOWZ7/bTTxPQt5VXf41mxq929h8E71cy5+jET9dNtiXc98MeGunumm2mM+K5RHtuoCYNMxaBTQL5PJJl7FbRh0T2NWxj7e1kYVTmH2BwzT7dc64QHBog3cdTj49WVIFRdjwQ2c3pU7QFpcBBn/3xek8kOcrUaYINuLL0sOVYW7WNcBXjoUaZYjZvF9auhFBJF3SRPWS8xVOx1s0h9sCn50/EuWYmAmmc8nlCJom/3Jl2vL936ZtfnOfFOht+2Q3BMJ0YiBqcG8V4wlnpKfEslTAnzRwd2Pk5587QThKbbNMV0adDzWbq+/RXz4GWcFsH7AxqPN4iDPKm/VqlxKEv3oNuvgBRqonn4yVhC36d+EzPvIzsCe/AlQ+AvlTgsqIrDmXmg/ccs2+hsBeumv/gZ+G01A4ilizAm6Tu6B3o/jTuFg6C8WXtp/6cqmohphUUFQ1VYFY+90FTuwL1l/4SYQrM6O/wyPa7Ly2+NSksQb6r/LN15dpIt3iuuxo8rxnFbwdm2XTvgUdtJjoR7ZgJHfvxY235z5PMhuCcWW3Prn9r1LYpMm8cyVDG6z3MxpI4Wuv4LswjE870557TUi9w4NTLq8OsPXR64=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
